# Generated by Django 5.2.1 on 2025-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PERISHABLE', 'PERISHABLE'), ('GRAINS', 'GRAINS'), ('VEGETABLES', 'VEGETABLES')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
