# Generated by Django 5.2.1 on 2025-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
